# Generated by Django 4.2 on 2023-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_alter_cart_pid_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
